{% set version = "1.16.2" %}

package:
  name: automake
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/automake/automake-{{ version }}.tar.gz
  sha256: b2f361094b410b4acbf4efba7337bdb786335ca09eb2518635a09fb7319ca5c1
  patches:
    - 0001-apple-silicon.patch
    - 0002-apple-silicon.patch

build:
{% if bootstrapping == 'yes' %}
  # Please increment by two
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  # Keep above the number of the _bootstrapping package
  number: 3
{% endif %}
  detect_binary_files_with_prefix: false
  script_env:
    - BOOTSTRAPPING={{ bootstrapping }}
  skip: true  # [win]

requirements:
{% if bootstrapping != 'yes' %}
  build:
    - make
  host:
    - m4
    - autoconf
    - perl
    - make
  run:
    - m4
    - autoconf
    - perl
{% endif %}

test:
  commands:
    - automake --help

about:
  home: http://www.gnu.org/software/automake/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Tool for automatically generating Makefile.in files compliant with the GNU Coding Standards.
  description: |
    Automake is a tool for automatically generating Makefile.ins from files
    called Makefile.am.  It assumes that the project uses Autoconf and enforces
    certain restrictions on the configure.ac contents.
  dev_url: https://git.savannah.gnu.org/git/automake.git
  doc_url: https://www.gnu.org/software/automake/manual/automake.html
  doc_source_url: http://git.savannah.gnu.org/cgit/automake.git/tree/doc

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - mingwandroid
