{% set version = "1.15" %}

package:
    name: automake
    version: {{ version }}

source:
    fn: automake-{{ version }}.tar.gz
    url: http://ftp.gnu.org/gnu/automake/automake-{{ version }}.tar.gz
    sha256: 7946e945a96e28152ba5a6beb0625ca715c6e32ac55f2e353ef54def0c8ed924

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - m4
        - autoconf
        - perl
    run:
        - m4
        - autoconf
        - perl

test:
    commands:
        - automake --help

about:
    home: http://www.gnu.org/software/automake/
    license: GPL 3
    summary: Tool for automatically generating Makefile.in files compliant with the GNU Coding Standards.

extra:
    recipe-maintainers:
        - jakirkham
        - ocefpaf
